### ISSUE TITLE
Allow Migrator.up to apply all newer migrations

### ISSUE THREAD

**Issue by daveyarwood** [SkylerLipthay/schemamama#3]
[`Migrator.down` has on optional version argument](https://github.com/SkylerLipthay/schemamama/blob/master/src/lib.rs#L131), but it looks like [`Migrator.up`'s version argument is required](https://github.com/SkylerLipthay/schemamama/blob/master/src/lib.rs#L157). Is there a reason that the version is required when migrating up? I feel like it would be useful if you could pass in `None`, and it would apply all migrations above the current versions.

If you agree, I can take a stab at a PR!

**Comment by SkylerLipthay** [comment]
I believe when I coded this I drew my inspiration from Rails migrations, which follow the same exclusive down/inclusive up pattern. So `down` is saying "run all downward migrations except the provided version" and `up` is saying "run all upward migrations including the provided version"...

Yeah, I'm struggling to find a reason why this convenience interface should not be implemented!  I would gladly review and merge a PR.
